import type { Metadata } from 'next'
import { Oxanium } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { cn } from '@/lib/utils'
import { TracingBeam } from '@/components/ui/tracing-beam'
import Footer from '@/components/Footer'

const oxanium = Oxanium({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='!scroll-smooth'>
      <body className={cn('bg-background-second text-text', oxanium.className)}>
        <TracingBeam>
          <Navbar />
          {children}
        </TracingBeam>
        <Footer />
      </body>
    </html>
  )
}
